debug: true
server:
    port: 8090
management:
    context-path: /dev
    security.enabled: false
spring:
    jackson:
        serialization.indent_output: true
    profiles:
        active: @profiles@