debug: false
server:
    port: 8090
spring:
    jackson:
        serialization.indent_output: true
    jpa:
        properties:
            hibernate:
            ddl-auto: validate
            format_sql: true
            id.new_generator_mappings: true
    ldap:
        embedded:
            base-dn: dc=thradec,dc=cz
            ldif: classpath:ldap-users.ldif
logging.level.org.hibernate.SQL: debug
management.endpoints.web.expose: "*"